#!/bin/sh

var=$(du -a ../src | awk '/java/ {print $2}' | wc -l)
name='GIRAUD-RENARD'

if [ -z "$1" ] #no file specified
then 

    if (( $var > 1 ))
    then 
        ls ../src/*.java | cut -d/ -f3 | cut -d. -f1
        read -p 'Vous souhaitez executer ? : ' choix
        javac -d ../class ../src/"$choix".java
        java -classpath ../class -Xss20000000 "$choix"
    else #if there is only one file, run it
        javac -d ../class ../src/*.java
        java -classpath ../class -Xss20000000 $(ls ../src/*.java | cut -d/ -f3 | cut -d. -f1)
    fi
    
elif [ "$1" = "all" ] #compile all
then 
    du -a ../src | awk '/java/ {print $2}' | xargs -r javac -d ../class
    
elif [ "$1" = "javadoc" ] #generate the javadoc
then
    du -a ../src | awk '/java/ {print $2}' | xargs -r javadoc -private -author -d ../javaDoc
    
elif [ "$1" = "compress" ] #create a .zip with the javadoc all the files
then
    directory=$(pwd | rev | cut -d/ -f2 | rev)
    du -a ../src | awk '/java/ {print $2}' | xargs -r javadoc -private -author -d ../javaDoc
    cd ../src
    zip -r ../$name-$directory *
    cd ..
    zip -r $name-$directory javaDoc/*
    
else #we have specified a file
    if [ "$2" = "a" ] #compile all before run the program
    then 
        du -a ../src | awk '/java/ {print $2}' | xargs -r javac -d ../class
    else
         javac -d ../class ../src/"$1".java
    fi
    java -classpath ../class -Xss20000000 "$1"
fi
